global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Def>
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is >

  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080'] # cambiar a la ip del host en caso de que no funcione

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node_exporter:9100']
    #metrics_path: '/metrics'
    #metrics_path: '/prometheus'
